version: '3'
services:
  mysqldb:
    image: mysql:latest
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: ticweb
      MYSQL_USER: f460c882a18
      MYSQL_PASSWORD: 89fb9a42628f26
    volumes:
      - ./db/mysql:/var/lib/mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
  mongodb:
    image: mongo:latest
    restart: always
    command: mongod --smallfiles
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootadmin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./db/mongodb:/data/db
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  account.api:
    build:
      context: .
      dockerfile: ./microservices/accountManager/Dockerfile
    depends_on:
      - mysqldb
    command: >
      bash -c "cd /var/www/html
      && composer install
      && composer update
      && php artisan migrate:fresh
      && php artisan db:seed
      && apachectl -D FOREGROUND"
    ports:
      - 8081:80
    tty: true
    restart: on-failure
    volumes:
      - ./microservices/accountManager/www:/var/www/html
    links:
      - mysqldb:mysql
  crime.api:
    build:
      context: .
      dockerfile: ./microservices/crimeManager/Dockerfile
    depends_on:
      - mongodb
    command: >
      bash -c "cd /var/www/html
      && composer install
      && composer update
      && apachectl -D FOREGROUND"
    ports:
      - 8083:80
    tty: true
    restart: on-failure
    volumes:
      - ./microservices/crimeManager/www:/var/www/html
    links:
      - mongodb:mongo
      - account.api
  web.api:
    image: node:latest
    command: >
      bash -c "cd /usr/src/app
      && npm install -g nodemon
      && npm install
      && npm start"
    ports:
      - 8084:80
    expose: 
      - 80
    tty: true
    restart: on-failure
    volumes:
      - ./webApi:/usr/src/app
    links:
      - account.api
      - crime.api
  web.client:
    image: vuejs/ci:latest
    command: >
      bash -c "cd /usr/src/app
      && npm install
      && npm run dev"
    ports:
      - 8085:80
    expose: 
      - 80
    tty: true
    restart: on-failure
    volumes:
      - ./webClient:/usr/src/app
    links:
      - web.api