version: '3'
services:
  mysqldb:
    image: mysql:latest
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: ticweb
      MYSQL_USER: f460c882a18
      MYSQL_PASSWORD: 89fb9a42628f26
    volumes:
      - ./db/mysql:/var/lib/mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
  mongodb:
    image: mongo:latest
    restart: always
    command: mongod --smallfiles
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootadmin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./db/mongodb:/data/db
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  account.api:
    build:
      context: .
      dockerfile: ./microservices/accountManager/Dockerfile
    ports:
      - 8081:80
    restart: always
    tty: true
    volumes:
      - ./microservices/accountManager/www:/var/www/html
    links:
      - mysqldb:mysql